### ISSUE TITLE
Failed to build on Windows. 'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by emilium** [siilisolutions-pl/room-booking-app#6]
I'm trying to build on Windows and it fails.

Error:

```
'rm' is not recognized as an internal or external command
```

Solution:

```
Use rimraf instead of `rm -rf` 
```

**Comment by tjankowski** [comment]
Hi @emilium,
Sorry for late response. Could you verify if #8 resolves your issue? If yes I will merge it and release new version of the application.

**Comment by emilium** [comment]
Hi @tjankowski, it's perfect now. Thank you.
